### ISSUE TITLE
项目中遇到的问题解决

### ISSUE THREAD

**Issue by 7986LiChang** [7986LiChang/todo-by-react#1]
#### 1）要实现整个**界面的高度和宽度始终保持和浏览器窗口大小一致**
- 页面的容器可以包括：屏幕、浏览器、页面。html元素展现在页面内，页面展现在浏览器内，而浏览器展现在屏幕内。
- 容器的尺寸是指当前分辨率下的高度、宽度，而不是物理高度、宽度。例如，22寸的显示器，屏幕分辨率为1366*768，获取到的屏幕高度即为1366px，宽度为768px
- 屏幕、浏览器、以及页面等高度
   - 屏幕信息
screen.height 屏幕高度
screen.width 屏幕宽度
screen.availHeight 屏幕可用高度。不含上下任务栏
screen.availWidth 屏幕可用宽度。不含左右任务栏
  - 浏览器信息，滚动距离
window.outerHeight 浏览器高度，包含工具栏
window.outerWidth 浏览器宽度
window.innerHeight 浏览器内页面可用高度，不含浏览器边框及工具条
window.innerWidth 浏览器内页面可用宽度，不含浏览器边框
window.pageYOffset/window.pageXOffset  页面/用户滚动的距离
  - 页面信息
document.body.offsetHeight body总高度，包含滚动条时的全部高度
document.body.offsetWidth body总宽度，包含滚动条的全部宽度
document.body.clientHeight 当前在浏览器内展示出的body高度（还有部分因滚动被隐藏）
document.body.clientWidth 当前在浏览器内展示出的width宽度（还有部分因滚动被隐藏）
#### 展示图
![qq 20170802171947](https://user-images.githubusercontent.com/14882636/28866893-f5b8f9aa-77a6-11e7-942a-e59791103d70.png)

#### 3）事件中的坐标 event.
- event.pageX/pageY : 事件相对于html元素的坐标
- event.clientX/clientY : 事件相对于viewport的位置坐标，即浏览器窗口
- event.screenX/screenY : 事件相对于屏幕，即设备像素的位置坐标
- event.offsetX/offsetY : 点击位置相对于触发事件元素左上角的偏移
- target.offsetLeft/target.offsetTop：触发事件的元素本身左上角在浏览器中的偏移量

#### 4）浮动溢出
css中使用浮动后，元素会脱离正常文本流，使得子元素漂浮而无法撑开父元素，需要清除浮动，从而使得父容器包含浮动元素。
- 解决方法1：使用带clear属性的空元素
在浮动元素后使用一个空元素，如`<div class="clear"></div>`，并在css中赋予`.clear{ clear: both }`。这样父元素就会按照预期包含子元素。
例如：
```css
.news {
  background-color: gray;
  border: solid 1px black;
  }

.news img {
  float: left;
  }

.news p {
  float: right;
  }

.clear {
  clear: both;
  }
```
```html
<div class="news">
<img src="news-pic.jpg" />
<p>some text</p>
<div class="clear"></div>
</div>
```
- 使用css的 :after伪元素。
是伪元素，而不是伪类。
给包含浮动元素的父容器添加一个clearfix的class，在class中添加 :after伪元素，实现在元素末尾添加看不见的块元素（block），从而实现清除浮动。同时，为了适应IE6/IE7，需要给clearfix的class添加`zoom:1 ;`从而触发haslayout
例如：
```css
.news {
  background-color: gray;
  border: solid 1px black;
  }

.news img {
  float: left;
  }

.news p {
  float: right;
  }

.clearfix:after{
  content: "020";    //带有内容，但是被隐藏
  display: block; 
  height: 0; 
  clear: both; 
  visibility: hidden;  
  }

.clearfix {
  /* 触发 hasLayout */ 
  zoom: 1; 
  }
```
```html
<div class="news clearfix">
    <img src="news-pic.jpg" />
    <p>some text</p>
</div>

```
- 使用css的overflow属性
给包含浮动元素的父元素添加`overflow:hidden;`或者`overflow:auto;`可以清除浮动。为了适应IE6需要触发hasLayout，为父元素设置zoom:1 或给父元素设置宽高
例如：
```css
.news {
  background-color: gray;
  border: solid 1px black;
  overflow: hidden;
  *zoom: 1;
  }

.news img {
  float: left;
  }

.news p {
  float: right;
  }
```
```html
<div class="news">
    <img src="news-pic.jpg" />
    <p>some text</p>
</div>
```

#### 5）content属性
配合 :before  :after伪元素使用，用于定义元素之前或之后放置生成的内容。一般默认是行内内容

#### 6）在css中给一个元素添加多个类，要用空格分开类名
例如：
```html
<body>
<h1 class="intro important">Header 1</h1>
<p>A paragraph.</p>
</body>
```
```css
h1.intro
{
color:blue;
text-align:center;
}
.important {background-color:yellow;}
```
#### 7）为元素设定height:100%不起作用
根据W3C规范，百分比的高度在设定时需要根据元素父容器的高度，若某div高度为height: 50%; 父元素高度是100px，则该div高度是50px。
> Web浏览器如何计算宽度和高度？
> - Web浏览器在计算有效宽度时，会考虑浏览器窗口的打开宽度，如果不给宽度设定任何缺省值，浏览器会自动将页面内容平铺填满整个横向宽度
> - 但高度计算方式不同。页面没有缺省的高度值，浏览器不会计算内容的高度，除非给元素设定了绝对高度，或内容超出视窗范围（导致滚动条出现），否则浏览器会简单让内容往下堆砌，无需考虑页面高度。
> - 因此，当给元素设定百分比高度时，除非父元素设定了绝对高度，否则根本无法获取父元素的高度，也就无法计算自己的高度。

若想让元素的百分比高度 height:100%;有效，必须**为该元素的所有父元素高度都设定一个有效值**，注意是所有，每一层父元素都必须设置height:100%，或保证其有绝对高度。一直延伸到<html>高度为100%时，即浏览器窗口高度。如：
```html
<html style="height: 100%;">
  <body style="height: 100%;">
    <div style="height: 100%;">
      <p>
        这样这个div的高度就会100%了
      </p>
    </div>
  </body>
</html>
```
使用height:100%要注意：
1）margin 和 padding会让页面出现滚动条，并不是希望的
2）若元素的实际高度大于设定的百分比，元素高度会自动扩展

#### 8）css中的选择器
div, p{ } 选择所有div和p元素
div p{ } 选择div内部的所有p元素，有层级关系
div>p 选择父元素为div的所有p元素
div+p 选择紧接在div元素后的所有p元素
p:before  在每个p元素的内容之前插入内容
p:after 在每个p元素的内容之后插入内容

#### 9）实现三栏式布局，可以左右两栏宽度固定，中间栏宽度自适应
可以有三种实现方式
- 使用自身浮动
左元素左浮动，右元素右浮动，主体直接放后面，利用标签跟随浮动的特性。特别注意：html中的div顺序：主体div只能放在最后，左右两侧div顺序随意
例如：**（即要自适应的元素放在最后）**
 ```html
 <div>
  	<div id="left"></div>
  	<div id="right"></div>
  	<div id="main"></div>
  </div>
```
```css
  <style type="text/css">
  	html, body{
  		margin: 0;
  		height: 100%;
  	}
  	#left{
  		float: left;
  	}
  	#right{
  		float: right;
  	}
  	#left, #right{
  		width: 200px;
  		height: 100%;
  		background: #a0b3d6;
  	}
  	#main{
  		height: 100%;
  		margin: 0 210px;   //利用左右margin自动撑开元素宽度
  		background: #ffe6b8;
  	}
  </style>
```
- 绝对定位法
- margin 负值法

#### 8）让浏览器默认不出现导航条
`overflow: hidden;`
